import Config

# Configure your database
# Use PostgreSQL if environment variables are set, otherwise use SQLite
if System.get_env("GAMEND_DB_URL") ||
     (System.get_env("GAMEND_DB_POSTGRES_HOST") && System.get_env("GAMEND_DB_POSTGRES_USER")) do
  # Use PostgreSQL when configured
  database_url =
    System.get_env("GAMEND_DB_URL") ||
      "ecto://#{System.get_env("GAMEND_DB_POSTGRES_USER")}:#{System.get_env("GAMEND_DB_POSTGRES_PASSWORD")}@#{System.get_env("GAMEND_DB_POSTGRES_HOST")}:#{System.get_env("GAMEND_DB_POSTGRES_PORT", "5432")}/#{System.get_env("GAMEND_DB_POSTGRES_DB", "game_server_dev")}"

  config :game_server_core, GameServer.Repo,
    url: database_url,
    adapter: Ecto.Adapters.Postgres,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
else
  # Fallback to SQLite when no PostgreSQL config
  database_path = Path.expand("../db/game_server_dev.db", __DIR__)
  File.mkdir_p!(Path.dirname(database_path))

  config :game_server_core, GameServer.Repo,
    database: database_path,
    adapter: Ecto.Adapters.SQLite3,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :game_server_web, GameServerWeb.Endpoint,
  # Binding to all interfaces to allow access from Docker host and other machines.
  # In Docker containers, bind to 0.0.0.0 to accept external connections.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:game_server_web, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:game_server_web, ~w(--watch)]}
  ]

config :game_server_web,
  session_secure: false,
  gzip_static: false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :game_server_web, GameServerWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"(?:apps/game_server_web/)?priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"(?:apps/game_server_web/)?priv/gettext/.*(po)$",
      ~r"(?:apps/game_server_web/)?lib/game_server_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :game_server_web, dev_routes: true

# Keep local development logs readable by default. Set GAMEND_OBSERVABILITY_LOG_LEVEL=debug when
# request/SQL traces are needed.
config :logger, level: :info
config :logger, :default_formatter, format: "[$level] $message\n"

# Also persist dev logs to a rotating file (10MB x 5, see
# GameServerWeb.FileLogHandler). Without this the only copy of a run is the
# terminal scrollback, so anything after the fact — grepping a run that already
# finished — depends on having captured it by hand. Writes alongside stdout, so
# the console is unchanged. LOG_FILE_PATH overrides the location.
config :game_server_web, :log_file, "log/dev.log"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# The mailer is configured for every environment in host_runtime.exs, from the
# declared GameServer.Mail settings.

# Configure Guardian for development
config :game_server_web, GameServerWeb.Auth.Guardian,
  issuer: "game_server",
  secret_key: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO",
  ttl: {15, :minutes}

# Looser throttling for local iteration. These were previously the *implicit*
# dev values — the production numbers only ever applied inside runtime.exs's
# prod branch, so dev silently got the code defaults. Now that the declared
# defaults are the production ones, dev asks for the slack explicitly.
config :game_server_web, GameServerWeb.Plugs.RateLimiter,
  general_limit: 1200,
  auth_limit: 30,
  ws_limit: 300,
  dc_limit: 600

# The declared setting, not just the endpoint's copy: GameServer.Settings
# validates `auth.secret_key_base` at boot, and dev should not warn about a
# secret it demonstrably has.
config :game_server_core, GameServer.Accounts,
  secret_key_base: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO"
