import Config

# Configure your database
# Use PostgreSQL if environment variables are set, otherwise use SQLite
if System.get_env("GAMEND_DB_URL") ||
     (System.get_env("GAMEND_DB_POSTGRES_HOST") && System.get_env("GAMEND_DB_POSTGRES_USER")) do
  # Use PostgreSQL when configured
  database_url =
    System.get_env("GAMEND_DB_URL") ||
      "ecto://#{System.get_env("GAMEND_DB_POSTGRES_USER")}:#{System.get_env("GAMEND_DB_POSTGRES_PASSWORD")}@#{System.get_env("GAMEND_DB_POSTGRES_HOST")}:#{System.get_env("GAMEND_DB_POSTGRES_PORT", "5432")}/#{System.get_env("GAMEND_DB_POSTGRES_DB", "gamend_dev")}"

  config :gamend_core, Gamend.Repo,
    url: database_url,
    adapter: Ecto.Adapters.Postgres,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
else
  # Fallback to SQLite when no PostgreSQL config
  database_path = Path.expand("../db/game_server_dev.db", __DIR__)
  File.mkdir_p!(Path.dirname(database_path))

  config :gamend_core, Gamend.Repo,
    database: database_path,
    adapter: Ecto.Adapters.SQLite3,
    # Match production: see the note in config/host_runtime.exs. Top-level
    # options, not a `pragmas:` list — ecto_sqlite3 has no such key and
    # silently ignores it. Without an explicit busy_timeout exqlite waits
    # 2000ms, which ten pooled writers on one file blow straight through:
    # concurrent device logins raised `Exqlite.Error: Database busy`.
    default_transaction_mode: :immediate,
    journal_mode: :wal,
    busy_timeout: 10_000,
    # Never let the query timeout fire before SQLite has stopped waiting.
    timeout: 15_000,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    # One connection, matching the production default for SQLite: more
    # connections race for the single write lock rather than sharing it, and
    # concurrent account creation went from 10s+ (and 500s) to ~60ms when this
    # dropped from 10 to 1. See the note in `GamendWeb.HostRuntime`.
    pool_size: 1
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :gamend_web, GamendWeb.Endpoint,
  # Binding to all interfaces to allow access from Docker host and other machines.
  # In Docker containers, bind to 0.0.0.0 to accept external connections.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  # Off under GAMEND_DEV_BENCH (see the phoenix_live_view block below). The
  # reloader checks every path dep for staleness on each request, and a
  # benchmark that includes that measures Mix: stress/README.md records 293
  # req/s in dev against 18,918 in prod for the same scenario.
  code_reloader: System.get_env("GAMEND_DEV_BENCH") not in ["1", "true"],
  debug_errors: true,
  secret_key_base: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:gamend_web, ~w(--sourcemap=inline --watch)]},
    # `assets/js/host_hooks.js` is its own bundle, not part of the web app's, so
    # the watcher above never sees it. Without this entry an edit there is
    # invisible in dev until someone runs `mix assets.build`.
    host_hooks: {Esbuild, :install_and_run, [:gamend_host_hooks, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:gamend_web, ~w(--watch)]}
  ]

config :gamend_web,
  session_secure: false,
  gzip_static: false

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :gamend_web, GamendWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"(?:apps/gamend_web/)?priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"(?:apps/gamend_web/)?priv/gettext/.*(po)$",
      ~r"(?:apps/gamend_web/)?lib/gamend_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :gamend_web, dev_routes: true

# Keep local development logs readable by default. Set GAMEND_OBSERVABILITY_LOG_LEVEL=debug when
# request/SQL traces are needed.
config :logger, level: :info
# `client_session` is included so correlating a client's logs with the server's
# behaves the same locally as in production. Without it the join silently works
# only once deployed, which is the worst place to discover it.
#
# This list is a deliberate subset of host_config.exs's — `request_id` on every
# line is noise locally — but any key a `Logger` call passes explicitly has to
# be here or the formatter drops it, so the payment-failure keys are repeated.
# `mix credo --strict` runs in dev and fails on a key that is logged but not
# listed, which is what keeps the two in sync.
config :logger, :default_formatter,
  format: "[$level] $metadata$message\n",
  metadata: [
    :client_session,
    :order_id,
    :provider,
    :provider_reason,
    :purchase_id,
    :reason
  ]

# Also persist dev logs to a rotating file (10MB x 5, see
# GamendWeb.FileLogHandler). Without this the only copy of a run is the
# terminal scrollback, so anything after the fact — grepping a run that already
# finished — depends on having captured it by hand. Writes alongside stdout, so
# the console is unchanged. LOG_FILE_PATH overrides the location.
config :gamend_web, :log_file, "log/dev.log"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# `GAMEND_DEV_BENCH=1` turns the dev server into a benchmark target: no code
# reloader, no HEEx annotations, no expensive runtime checks. Invaluable while
# editing, ruinous while measuring — the annotations alone add ~1.3 KB to every
# link. Borrowed from gamend_polyglot, which found both costs first.
#
# The annotations are compiled into templates, so run it with its own build
# path (`MIX_BUILD_PATH=_build/bench`, as the `gamend-bench` launch config
# does) rather than `mix clean`ing the normal one on every toggle.
bench? = System.get_env("GAMEND_DEV_BENCH") in ["1", "true"]

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: not bench?,
  debug_attributes: not bench?,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: not bench?

# The mailer is configured for every environment in host_runtime.exs, from the
# declared Gamend.Mail settings.

# Configure Guardian for development
config :gamend_web, GamendWeb.Auth.Guardian,
  issuer: "gamend",
  secret_key: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO"

# Looser throttling for local iteration. These were previously the *implicit*
# dev values — the production numbers only ever applied inside runtime.exs's
# prod branch, so dev silently got the code defaults. Now that the declared
# defaults are the production ones, dev asks for the slack explicitly.
config :gamend_web, GamendWeb.Plugs.RateLimiter,
  general_limit: 1200,
  auth_limit: 30,
  ws_limit: 300,
  dc_limit: 600

# The declared setting, not just the endpoint's copy: Gamend.Settings
# validates `auth.secret_key_base` at boot, and dev should not warn about a
# secret it demonstrably has.
config :gamend_core, Gamend.Accounts,
  secret_key_base: "l/tTJZ4KUNjIfiUsNQDQLWOTgFlyiOz8RQ2EgSRa7mopMzPLJuu7/8s5pA7iiSgO"
