defmodule Mix.Tasks.Gamend.Settings.EnvExample do
  @shortdoc "Regenerates .env.example from the declared settings"

  @moduledoc """
  Writes `.env.example` from `GameServer.Settings.all/0`, grouped and
  commented from each setting's declaration.

      mix gamend.settings.env_example          # write .env.example
      mix gamend.settings.env_example --check  # fail if it is out of date
      mix gamend.settings.env_example -o PATH  # write somewhere else

  The file was hand-maintained until now, and drifted: 31 variables the code
  reads were documented nowhere. Generating it means a setting is documented
  the moment it is declared, and `--check` keeps it that way in CI.
  """

  use Mix.Task

  alias GameServer.Settings

  @impl true
  def run(argv) do
    Mix.Task.run("app.config")

    {opts, _rest} =
      OptionParser.parse!(argv, strict: [check: :boolean, output: :string], aliases: [o: :output])

    path = Keyword.get(opts, :output, ".env.example")
    generated = render()

    if Keyword.get(opts, :check, false) do
      check(path, generated)
    else
      File.write!(path, generated)
      Mix.shell().info("wrote #{path} (#{length(Settings.all())} settings)")
    end
  end

  defp check(path, generated) do
    case File.read(path) do
      {:ok, ^generated} ->
        Mix.shell().info("#{path} is up to date")

      {:ok, _stale} ->
        Mix.raise("#{path} is out of date. Run: mix gamend.settings.env_example")

      {:error, _reason} ->
        Mix.raise("#{path} does not exist. Run: mix gamend.settings.env_example")
    end
  end

  @doc false
  def render do
    [header(), Enum.map(Settings.groups(), &group_section/1)]
    |> IO.iodata_to_binary()
  end

  defp header do
    """
    # Generated by `mix gamend.settings.env_example` — do not edit by hand.
    #
    # Every variable below is declared with GameServer.Settings.Provider, which
    # is also what the admin Settings page renders. Values shown are defaults;
    # a commented line means the default applies when the variable is unset.
    #
    # Every name is derived from its declaration as GAMEND_<GROUP>_<KEY>, with
    # no exceptions. Variables other software reads (RELEASE_COOKIE for the
    # release boot script, FLY_* from the platform) are not settings and are
    # not listed here.
    #
    # Settings can equally be configured in Elixir, which skips this file
    # entirely:
    #
    #     config :game_server_core, GameServer.Retention, chat_messages_days: 90
    """
  end

  defp group_section({group, label}) do
    settings = Settings.group(group)

    [
      "\n# ",
      String.duplicate("─", 74),
      "\n# ",
      label,
      "\n# ",
      String.duplicate("─", 74),
      "\n",
      Enum.map(settings, &setting_lines/1)
    ]
  end

  defp setting_lines(definition) do
    [
      "\n",
      doc_lines(definition),
      annotations(definition),
      assignment(definition)
    ]
  end

  defp doc_lines(%{doc: ""}), do: []

  defp doc_lines(%{doc: doc}) do
    doc
    |> wrap(74)
    |> Enum.map(&["# ", &1, "\n"])
  end

  defp annotations(definition) do
    [
      requirement_note(definition),
      if(definition.secret, do: "# Secret — never commit a real value.\n", else: [])
    ]
  end

  defp requirement_note(%{required: nil}), do: []

  defp requirement_note(%{required: level} = definition) do
    consequence =
      case level do
        :prod -> "REQUIRED in production — the server refuses to start without it"
        :warn -> "Expected in production — logs a warning when missing"
      end

    ["# ", consequence, gate_note(definition), ".\n"]
  end

  defp gate_note(%{when: nil} = definition), do: with_note(definition)

  defp gate_note(%{when: {[group, key], value}} = definition) do
    [
      ", when ",
      to_string(group),
      ".",
      to_string(key),
      " is ",
      inspect(value),
      with_note(definition)
    ]
  end

  defp gate_note(%{when: conditions} = definition) when is_list(conditions) do
    clauses =
      Enum.map_join(conditions, " and ", fn {[group, key], value} ->
        "#{group}.#{key} is #{inspect(value)}"
      end)

    [", when ", clauses, with_note(definition)]
  end

  defp with_note(%{with: []}), do: []

  defp with_note(%{with: siblings}) do
    [", if any of ", Enum.map_join(siblings, "/", &to_string/1), " is set"]
  end

  defp assignment(%{env: env, default: default}) do
    case format_default(default) do
      nil -> ["# ", env, "=\n"]
      value -> ["# ", env, "=", value, "\n"]
    end
  end

  defp format_default(nil), do: nil
  defp format_default([]), do: nil
  defp format_default(true), do: "true"
  defp format_default(false), do: "false"
  defp format_default(value) when is_list(value), do: Enum.join(value, ",")
  defp format_default(value) when is_binary(value), do: value
  defp format_default(value), do: to_string(value)

  # Keeps generated comments inside a readable column without depending on the
  # doc strings being pre-wrapped.
  defp wrap(text, width) do
    text
    |> String.split(~r/\s+/, trim: true)
    |> Enum.reduce([], fn word, lines ->
      case lines do
        [] ->
          [word]

        [current | rest] ->
          if String.length(current) + 1 + String.length(word) <= width do
            [current <> " " <> word | rest]
          else
            [word, current | rest]
          end
      end
    end)
    |> Enum.reverse()
  end
end
