defmodule Mix.Tasks.Gamend.Content.Extract do
  @shortdoc "Extracts quest/leaderboard/tournament text into a gettext POT template"

  @moduledoc """
  Writes `content.pot` from the titles and descriptions stored on quests,
  leaderboards and tournaments.

      mix gamend.content.extract          # write the template
      mix gamend.content.extract --check  # fail if it is out of date
      mix gamend.content.extract -o PATH  # write somewhere else

  ## Why from the database rather than from source

  The obvious approach is `dgettext_noop("content", "Welcome aboard")` at each
  definition site, letting `mix gettext.extract` find it. That does not work
  here, for two reasons:

    * **plugins cannot use it.** A plugin is its own Mix project and does not
      depend on `:gettext`, so the macro is not in scope — and plugins are
      where a game defines its content.
    * **it would miss everything an admin creates.** Admin-typed titles never
      appear in source at all.

  Reading the rows covers both, and matches how the theme is extracted: from
  the data, not from the code that produced it. Run it after seeding or after
  an admin adds content, then `mix gettext.merge` and translate.

  Text still reaches the database as the **source** string — never wrap a title
  in `gettext/1` at creation, or you freeze one locale in for every user.
  `GameServerWeb.ContentText` translates per viewer at render.
  """

  use Mix.Task

  import Ecto.Query

  alias GameServer.Repo

  @default_path "priv/gettext/content.pot"

  @sources [
    {GameServer.Quests.Quest, "quests"},
    {GameServer.Leaderboards.Leaderboard, "leaderboards"},
    {GameServer.Tournaments.Tournament, "tournaments"}
  ]

  @impl true
  def run(argv) do
    Mix.Task.run("app.start")

    {opts, _rest} =
      OptionParser.parse!(argv, strict: [check: :boolean, output: :string], aliases: [o: :output])

    path = Keyword.get(opts, :output, @default_path)
    strings = collect()

    cond do
      strings == [] ->
        Mix.shell().info("no quest/leaderboard/tournament text found - nothing to extract")

      Keyword.get(opts, :check, false) ->
        check(path, render(strings))

      true ->
        File.mkdir_p!(Path.dirname(path))
        File.write!(path, render(strings))
        Mix.shell().info("wrote #{path} (#{length(strings)} strings)")
    end
  end

  defp collect do
    @sources
    |> Enum.flat_map(fn {schema, label} ->
      schema
      |> from(select: [:title, :description])
      |> Repo.all()
      |> Enum.flat_map(fn row ->
        [{row.title, label}, {row.description, label}]
      end)
    end)
    |> Enum.reject(fn {text, _label} -> is_nil(text) or String.trim(text) == "" end)
    |> Enum.uniq_by(&elem(&1, 0))
  rescue
    # A task run against a database that has not been migrated should say so,
    # not crash with a table-missing error.
    error ->
      Mix.raise("could not read content: #{Exception.message(error)}")
  end

  defp check(path, generated) do
    case File.read(path) do
      {:ok, ^generated} -> Mix.shell().info("#{path} is up to date")
      {:ok, _stale} -> Mix.raise("#{path} is out of date. Run: mix gamend.content.extract")
      {:error, _} -> Mix.raise("#{path} does not exist. Run: mix gamend.content.extract")
    end
  end

  @doc false
  def render(strings) do
    header = """
    ## Generated by `mix gamend.content.extract` from the database.
    ## Do not edit by hand: edit the content, then re-run the task.
    ##
    ## Titles and descriptions of quests, leaderboards and tournaments. Whatever
    ## created them — a plugin, a seed, or an admin — the stored string is the
    ## msgid, and GameServerWeb.ContentText translates it per viewer.
    msgid ""
    msgstr ""
    "Language: en\\n"
    """

    header <> Enum.map_join(strings, "", fn {text, label} -> entry(text, label) end)
  end

  defp entry(text, label) do
    """

    #. #{label}
    msgid #{quote_po(text)}
    msgstr ""
    """
  end

  defp quote_po(string) do
    escaped = string |> String.replace("\\", "\\\\") |> String.replace("\"", "\\\"")

    case String.split(escaped, "\n") do
      [single] ->
        ~s("#{single}")

      lines ->
        body =
          lines
          |> Enum.with_index()
          |> Enum.map_join("\n", fn {line, index} ->
            suffix = if index == length(lines) - 1, do: "", else: "\\n"
            ~s("#{line}#{suffix}")
          end)

        ~s("") <> "\n" <> body
    end
  end
end
