defmodule Mix.Tasks.Gamend.Theme.Extract do
  @shortdoc "Extracts translatable theme strings into a gettext POT template"

  @moduledoc """
  Writes `theme.pot` from the strings in the theme config.

      mix gamend.theme.extract          # write the template
      mix gamend.theme.extract --check  # fail if it is out of date
      mix gamend.theme.extract -o PATH  # write somewhere else

  `mix gettext.extract` cannot find these: it scans source for `gettext(...)`
  calls, and theme text lives in data. This walks the config instead, using the
  same `GameServer.Theme.Translatable` list the renderer uses, so the strings a
  translator is offered are exactly the strings the server will translate.

  Merge into the per-locale PO files afterwards the usual way:

      mix gettext.merge priv/gettext
  """

  use Mix.Task

  alias GameServer.Theme.JSONConfig
  alias GameServer.Theme.Translatable

  # The host's own tree: a theme belongs to the host, so its translations do
  # too. Relative to the directory the task is run from, which is the host root.
  @default_path "priv/gettext/theme.pot"

  @impl true
  def run(argv) do
    Mix.Task.run("app.config")

    {opts, _rest} =
      OptionParser.parse!(argv, strict: [check: :boolean, output: :string], aliases: [o: :output])

    path = Keyword.get(opts, :output, @default_path)

    case JSONConfig.raw_theme() do
      config when map_size(config) == 0 ->
        Mix.shell().info("no theme config found - nothing to extract")

      config ->
        strings = Translatable.strings(config)
        generated = render(strings)

        if Keyword.get(opts, :check, false) do
          check(path, generated)
        else
          File.mkdir_p!(Path.dirname(path))
          File.write!(path, generated)
          Mix.shell().info("wrote #{path} (#{length(strings)} strings)")
        end
    end
  end

  defp check(path, generated) do
    case File.read(path) do
      {:ok, ^generated} -> Mix.shell().info("#{path} is up to date")
      {:ok, _stale} -> Mix.raise("#{path} is out of date. Run: mix gamend.theme.extract")
      {:error, _} -> Mix.raise("#{path} does not exist. Run: mix gamend.theme.extract")
    end
  end

  @doc false
  def render(strings) do
    header = """
    ## Generated by `mix gamend.theme.extract` from the theme config.
    ## Do not edit by hand: edit the text in the config, then re-run the task.
    ##
    ## Only the keys GameServer.Theme.Translatable lists are extracted, so
    ## configuration (urls, icons, colours, layout) never reaches a translator.
    msgid ""
    msgstr ""
    "Language: en\\n"
    """

    entries = Enum.map_join(strings, "", &entry/1)
    header <> entries
  end

  defp entry(string) do
    """

    msgid #{escape(string)}
    msgstr ""
    """
  end

  # PO quoting: a multi-line value becomes an empty first line followed by one
  # quoted line per source line, each keeping its trailing newline.
  defp escape(string) do
    escaped =
      string
      |> String.replace("\\", "\\\\")
      |> String.replace("\"", "\\\"")

    case String.split(escaped, "\n") do
      [single] ->
        ~s("#{single}")

      lines ->
        body =
          lines
          |> Enum.with_index()
          |> Enum.map_join("\n", fn {line, index} ->
            suffix = if index == length(lines) - 1, do: "", else: "\\n"
            ~s("#{line}#{suffix}")
          end)

        ~s("") <> "\n" <> body
    end
  end
end
